//Dans ReactionManager, y'a un import de GuildTextChannelManager, ce qu'il ne faut pas... Il faut que ca soit pour tous les types de channel, DM ou Guild...

/*export class DirectMessageManager {
    private channel = ChannelManager // DM / etc...
}*/